# Generated by Django 3.1.7 on 2021-03-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('city_can_go1', models.CharField(max_length=100)),
                ('city_can_go2', models.CharField(max_length=100)),
            ],
        ),
    ]
