# Generated by Django 3.1.7 on 2021-03-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cities_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='city_can_go3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
