# Generated by Django 3.1.7 on 2021-03-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='savedTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
