# Generated by Django 3.1.7 on 2021-03-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='arrivetime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
