# Generated by Django 3.1.7 on 2021-03-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20210325_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='arrivetime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
